### ISSUE TITLE
ERROR: Installation messages in R

### ISSUE THREAD

**Issue by rowantoday** [mwernerds/trajcomp#3]
**hello,Martin,
I get an error when installing TRACLUS. I have installed RTools in my computer. I can`t solve this problems,can you help me? This is the session info:**
 sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936  
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C  
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1

**This is the message stuff I get when installing trajcomp_0.2.tar.gz**
 install.packages("D:/RPackage/trajcomp_0.2.tar.gz", repos = NULL, type = "source")
- installing _source_ package 'trajcomp' ...
  *\* libs

**\* arch - i386
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"D:/R/R-3.3.1/include" -DNDEBUG "-I."   -I"D:/R/R-3.3.1/library/Rcpp/include" -I"D:/R/R-3.3.1/library/BH/include" -I"D:/R/R-3.3.1/library/RcppEigen/include" -I"D:/R/R-3.3.1/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"D:/R/R-3.3.1/include" -DNDEBUG "-I."   -I"D:/R/R-3.3.1/library/Rcpp/include" -I"D:/R/R-3.3.1/library/BH/include" -I"D:/R/R-3.3.1/library/RcppEigen/include" -I"D:/R/R-3.3.1/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c interrupt.cpp -o interrupt.o
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"D:/R/R-3.3.1/include" -DNDEBUG "-I."   -I"D:/R/R-3.3.1/library/Rcpp/include" -I"D:/R/R-3.3.1/library/BH/include" -I"D:/R/R-3.3.1/library/RcppEigen/include" -I"D:/R/R-3.3.1/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c public_api.cpp -o public_api.o
In file included from public_api.cpp:19:0:
./trajcomp/trajcomp_traclus.hpp:306:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
  #pragma omp parallel for
 ^
./trajcomp/trajcomp_traclus.hpp:309:0: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
   #pragma omp critical
 ^
./trajcomp/trajcomp_traclus.hpp:315:0: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
     #pragma omp critical
 ^
In file included from public_api.cpp:31:0:
persistence.hpp: In function 'void persistence::print_curve(persistence::Curve&)':
persistence.hpp:82:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < c.size(); i++){
                    ^
persistence.hpp: In function 'persistence::Curve persistence::traj_to_curve(const std::vectorstd::vector<double >&)':
persistence.hpp:97:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 0; i < t.size(); ++i){
                     ^
persistence.hpp:99:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(i == 0 || i == t.size()-1){
                    ^
persistence.hpp: In function 'persistence::Extrema persistence::extrema(const Curve&)':
persistence.hpp:148:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 1; i < curve.size(); ++i){
                     ^
In file included from public_api.cpp:31:0:
persistence.hpp: In function 'persistence::Curve persistence::betaPruning(const std::vectorpersistence::Bar&, const Curve&, double)':
persistence.hpp:227:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(b.min != 0 && b.min != end_p ){
                              ^
persistence.hpp:230:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(b.max != 0 && b.max != end_p ){
                              ^
persistence.hpp: In function 'persistence::Result persistence::PersistenceAlg(const Curve&, double, int)':
persistence.hpp:263:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < comps.size(); ++i){
                    ^
persistence.hpp:310:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if((curve[l].val < curve[r].val || r == curve.size())  && l != -1  ){
                                            ^
persistence.hpp:321:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(x == curve.size()){
            ^
persistence.hpp: In function 'persistence::Curve persistence::prune_curve_dist(const Curve&, double)':
persistence.hpp:389:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 1; i < curve.size()-1;  ++i){
                     ^
persistence.hpp: In function 'persistence::Curve persistence::prune_curve_dist_to_segment(const Curve&, double)':
persistence.hpp:418:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 1; i < curve.size()-1;  ++i){
                     ^
persistence.hpp: In function 'void persistence::recalc_angles_inplace(persistence::Curve&)':
persistence.hpp:437:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 0; i < curve.size(); ++i){
                     ^
persistence.hpp:439:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(i == 0 || i == curve.size()-1){
                    ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_curve(Rcpp::NumericMatrix)':
persistence.hpp:512:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_extrema(Rcpp::NumericMatrix)':
persistence.hpp:527:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_bars(Rcpp::NumericMatrix, Rcpp::NumericVector)':
persistence.hpp:546:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericMatrix persistence_pruned(Rcpp::NumericMatrix, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:565:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp:573:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < p_result.pruned.size(); i++){
                    ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_comps(Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:592:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.size(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_multires_index(Rcpp::NumericMatrix, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:611:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericMatrix PersistenceMRS(Rcpp::NumericMatrix, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:629:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                        ^
persistence.hpp:645:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < p_result.size(); i++){
                      ^
persistence.hpp: In function 'Rcpp::NumericMatrix PersistenceSDS(Rcpp::NumericMatrix, Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:668:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                        ^
persistence.hpp:677:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < p_result.size(); i++){
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_test_bars(Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:696:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.size(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_test_comps(Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:714:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.size(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp: In function 'Settings& getSettings(int)':
public_api.cpp:38:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (i<0 || i >= gSettings.size())
               ^
public_api.cpp: In function 'std::string encode_globaldirection(std::vectorstd::vector<double >, char, std::size_t)':
public_api.cpp:64:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(step == numChar) step -= numChar;
           ^
public_api.cpp: In function 'std::string encode_localdirection(std::vectorstd::vector<double >, char, std::size_t)':
public_api.cpp:86:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(step == numChar) step -= numChar;
           ^
public_api.cpp: In function 'std::string encode_length(std::vectorstd::vector<double >, double, char, std::size_t)':
public_api.cpp:102:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i=0; i < traj.size()-1; i++){
                   ^
public_api.cpp:118:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (step >= numChar) step = numChar-1;
            ^
public_api.cpp: In function 'std::string encode_globaldirectionFSP(std::vectorstd::vector<double >, char, std::size_t)':
public_api.cpp:135:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(step == numChar) step -= numChar;
             ^
public_api.cpp: In function 'std::string encode_lengthFSP(std::vectorstd::vector<double >, double, char, std::size_t)':
public_api.cpp:151:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i=0; i < traj.size()-1; i++){
                   ^
public_api.cpp:167:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (step >= numChar) step = numChar-1;
              ^
public_api.cpp: In function 'SEXPREC\* trajectory_distances(Rcpp::NumericMatrix, Rcpp::NumericMatrix, int)':
public_api.cpp:437:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < S.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp:439:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp:447:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < s.distances.size(); i++){
                    ^
public_api.cpp: In function 'Rcpp::NumericVector trajectory_distance_vector(Rcpp::NumericMatrix, Rcpp::NumericMatrix, int)':
public_api.cpp:490:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                       ^
public_api.cpp:496:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (size_t i=0; i <= S.nrow(); i++)  
                       ^
public_api.cpp:498:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      if (i == S.nrow()|| std::isnan(S(i,0))) // the last or any nan
            ^
public_api.cpp:503:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        for(int i = 0; i < s.distances.size(); i++){
                         ^
public_api.cpp: In function 'Rcpp::String encode(Rcpp::NumericMatrix, std::string)':
public_api.cpp:545:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp: In function 'Rcpp::NumericVector distance_vector_ddply(Rcpp::NumericMatrix, Rcpp::NumericMatrix, int)':
public_api.cpp:568:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < Q.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                        ^
public_api.cpp:571:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                        ^
public_api.cpp:580:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < s.distances.size(); i++){
                      ^
public_api.cpp: In function 'Rcpp::CharacterVector getDistanceNames(int)':
public_api.cpp:624:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i=0; i<s.distances.size(); i++){
                 ^
public_api.cpp: In function 'Rcpp::NumericMatrix DouglasPeucker(Rcpp::NumericMatrix, double)':
public_api.cpp:652:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < S.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp:660:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < res.size(); i++){
                    ^
public_api.cpp: In function 'Rcpp::NumericMatrix DouglasPeuckerWeights(Rcpp::NumericMatrix, double)':
public_api.cpp:680:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < S.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp:688:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < res.size(); i++){
                    ^
public_api.cpp: In function 'Rcpp::DataFrame cpp_traclus(Rcpp::NumericMatrix, double, int)':
public_api.cpp:822:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < TrajectoryDB.nrow(); i++)  //@todo: remove copy by an adapter class
                        ^
public_api.cpp: In function 'Rcpp::NumericVector trajectory_distance_vector(Rcpp::NumericMatrix, Rcpp::NumericMatrix, int)':
public_api.cpp:524:49: warning: 'd' may be used uninitialized in this function [-Wmaybe-uninitialized]
        for (auto p:distributor) distances[p] = d;
                                                 ^
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"D:/R/R-3.3.1/include" -DNDEBUG "-I."   -I"D:/R/R-3.3.1/library/Rcpp/include" -I"D:/R/R-3.3.1/library/BH/include" -I"D:/R/R-3.3.1/library/RcppEigen/include" -I"D:/R/R-3.3.1/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c redsvd.cpp -o redsvd.o
c:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o trajcomp.dll tmp.def RcppExports.o interrupt.o public_api.o redsvd.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LD:/R/R-3.3.1/bin/i386 -lR
installing to D:/R/R-3.3.1/library/trajcomp/libs/i386

**\* arch - x64
c:/Rtools/mingw_64/bin/g++  -std=c++0x -I"D:/R/R-3.3.1/include" -DNDEBUG "-I."   -I"D:/R/R-3.3.1/library/Rcpp/include" -I"D:/R/R-3.3.1/library/BH/include" -I"D:/R/R-3.3.1/library/RcppEigen/include" -I"D:/R/R-3.3.1/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -std=c++0x -I"D:/R/R-3.3.1/include" -DNDEBUG "-I."   -I"D:/R/R-3.3.1/library/Rcpp/include" -I"D:/R/R-3.3.1/library/BH/include" -I"D:/R/R-3.3.1/library/RcppEigen/include" -I"D:/R/R-3.3.1/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c interrupt.cpp -o interrupt.o
c:/Rtools/mingw_64/bin/g++  -std=c++0x -I"D:/R/R-3.3.1/include" -DNDEBUG "-I."   -I"D:/R/R-3.3.1/library/Rcpp/include" -I"D:/R/R-3.3.1/library/BH/include" -I"D:/R/R-3.3.1/library/RcppEigen/include" -I"D:/R/R-3.3.1/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c public_api.cpp -o public_api.o
In file included from public_api.cpp:19:0:
./trajcomp/trajcomp_traclus.hpp:306:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
  #pragma omp parallel for
 ^
./trajcomp/trajcomp_traclus.hpp:309:0: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
   #pragma omp critical
 ^
./trajcomp/trajcomp_traclus.hpp:315:0: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
     #pragma omp critical
 ^
In file included from public_api.cpp:31:0:
persistence.hpp: In function 'void persistence::print_curve(persistence::Curve&)':
persistence.hpp:82:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < c.size(); i++){
                    ^
persistence.hpp: In function 'persistence::Curve persistence::traj_to_curve(const std::vectorstd::vector<double >&)':
persistence.hpp:97:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 0; i < t.size(); ++i){
                     ^
persistence.hpp:99:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(i == 0 || i == t.size()-1){
                    ^
persistence.hpp: In function 'persistence::Extrema persistence::extrema(const Curve&)':
persistence.hpp:148:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 1; i < curve.size(); ++i){
                     ^
In file included from public_api.cpp:31:0:
persistence.hpp: In function 'persistence::Curve persistence::betaPruning(const std::vectorpersistence::Bar&, const Curve&, double)':
persistence.hpp:227:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(b.min != 0 && b.min != end_p ){
                              ^
persistence.hpp:230:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(b.max != 0 && b.max != end_p ){
                              ^
persistence.hpp: In function 'persistence::Result persistence::PersistenceAlg(const Curve&, double, int)':
persistence.hpp:263:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < comps.size(); ++i){
                    ^
persistence.hpp:310:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if((curve[l].val < curve[r].val || r == curve.size())  && l != -1  ){
                                            ^
persistence.hpp:321:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(x == curve.size()){
            ^
persistence.hpp: In function 'persistence::Curve persistence::prune_curve_dist(const Curve&, double)':
persistence.hpp:389:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 1; i < curve.size()-1;  ++i){
                     ^
persistence.hpp: In function 'persistence::Curve persistence::prune_curve_dist_to_segment(const Curve&, double)':
persistence.hpp:418:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 1; i < curve.size()-1;  ++i){
                     ^
persistence.hpp: In function 'void persistence::recalc_angles_inplace(persistence::Curve&)':
persistence.hpp:437:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(auto i = 0; i < curve.size(); ++i){
                     ^
persistence.hpp:439:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(i == 0 || i == curve.size()-1){
                    ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_curve(Rcpp::NumericMatrix)':
persistence.hpp:512:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_extrema(Rcpp::NumericMatrix)':
persistence.hpp:527:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_bars(Rcpp::NumericMatrix, Rcpp::NumericVector)':
persistence.hpp:546:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericMatrix persistence_pruned(Rcpp::NumericMatrix, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:565:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp:573:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < p_result.pruned.size(); i++){
                    ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_comps(Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:592:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.size(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_multires_index(Rcpp::NumericMatrix, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:611:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericMatrix PersistenceMRS(Rcpp::NumericMatrix, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:629:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                        ^
persistence.hpp:645:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < p_result.size(); i++){
                      ^
persistence.hpp: In function 'Rcpp::NumericMatrix PersistenceSDS(Rcpp::NumericMatrix, Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:668:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                        ^
persistence.hpp:677:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < p_result.size(); i++){
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_test_bars(Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:696:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.size(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
persistence.hpp: In function 'Rcpp::NumericVector persistence_test_comps(Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)':
persistence.hpp:714:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.size(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp: In function 'Settings& getSettings(int)':
public_api.cpp:38:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (i<0 || i >= gSettings.size())
               ^
public_api.cpp: In function 'std::string encode_globaldirection(std::vectorstd::vector<double >, char, std::size_t)':
public_api.cpp:64:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(step == numChar) step -= numChar;
           ^
public_api.cpp: In function 'std::string encode_localdirection(std::vectorstd::vector<double >, char, std::size_t)':
public_api.cpp:86:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(step == numChar) step -= numChar;
           ^
public_api.cpp: In function 'std::string encode_length(std::vectorstd::vector<double >, double, char, std::size_t)':
public_api.cpp:102:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i=0; i < traj.size()-1; i++){
                   ^
public_api.cpp:118:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (step >= numChar) step = numChar-1;
            ^
public_api.cpp: In function 'std::string encode_globaldirectionFSP(std::vectorstd::vector<double >, char, std::size_t)':
public_api.cpp:135:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(step == numChar) step -= numChar;
             ^
public_api.cpp: In function 'std::string encode_lengthFSP(std::vectorstd::vector<double >, double, char, std::size_t)':
public_api.cpp:151:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i=0; i < traj.size()-1; i++){
                   ^
public_api.cpp:167:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (step >= numChar) step = numChar-1;
              ^
public_api.cpp: In function 'SEXPREC\* trajectory_distances(Rcpp::NumericMatrix, Rcpp::NumericMatrix, int)':
public_api.cpp:437:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < S.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp:439:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp:447:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < s.distances.size(); i++){
                    ^
public_api.cpp: In function 'Rcpp::NumericVector trajectory_distance_vector(Rcpp::NumericMatrix, Rcpp::NumericMatrix, int)':
public_api.cpp:490:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                       ^
public_api.cpp:496:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (size_t i=0; i <= S.nrow(); i++)  
                       ^
public_api.cpp:498:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      if (i == S.nrow()|| std::isnan(S(i,0))) // the last or any nan
            ^
public_api.cpp:503:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        for(int i = 0; i < s.distances.size(); i++){
                         ^
public_api.cpp: In function 'Rcpp::String encode(Rcpp::NumericMatrix, std::string)':
public_api.cpp:545:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp: In function 'Rcpp::NumericVector distance_vector_ddply(Rcpp::NumericMatrix, Rcpp::NumericMatrix, int)':
public_api.cpp:568:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < Q.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                        ^
public_api.cpp:571:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < T.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                        ^
public_api.cpp:580:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < s.distances.size(); i++){
                      ^
public_api.cpp: In function 'Rcpp::CharacterVector getDistanceNames(int)':
public_api.cpp:624:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i=0; i<s.distances.size(); i++){
                 ^
public_api.cpp: In function 'Rcpp::NumericMatrix DouglasPeucker(Rcpp::NumericMatrix, double)':
public_api.cpp:652:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < S.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp:660:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < res.size(); i++){
                    ^
public_api.cpp: In function 'Rcpp::NumericMatrix DouglasPeuckerWeights(Rcpp::NumericMatrix, double)':
public_api.cpp:680:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i=0; i < S.nrow(); i++)  //@todo: remove copy by an adapter class @Martin
                      ^
public_api.cpp:688:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < res.size(); i++){
                    ^
public_api.cpp: In function 'Rcpp::DataFrame cpp_traclus(Rcpp::NumericMatrix, double, int)':
public_api.cpp:822:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i=0; i < TrajectoryDB.nrow(); i++)  //@todo: remove copy by an adapter class
                        ^
public_api.cpp: In function 'Rcpp::NumericVector trajectory_distance_vector(Rcpp::NumericMatrix, Rcpp::NumericMatrix, int)':
public_api.cpp:524:49: warning: 'd' may be used uninitialized in this function [-Wmaybe-uninitialized]
        for (auto p:distributor) distances[p] = d;
                                                 ^
c:/Rtools/mingw_64/bin/g++  -std=c++0x -I"D:/R/R-3.3.1/include" -DNDEBUG "-I."   -I"D:/R/R-3.3.1/library/Rcpp/include" -I"D:/R/R-3.3.1/library/BH/include" -I"D:/R/R-3.3.1/library/RcppEigen/include" -I"D:/R/R-3.3.1/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c redsvd.cpp -o redsvd.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o trajcomp.dll tmp.def RcppExports.o interrupt.o public_api.o redsvd.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LD:/R/R-3.3.1/bin/x64 -lR
installing to D:/R/R-3.3.1/library/trajcomp/libs/x64
*\* R
*\* data
*\* inst
*\* preparing package for lazy loading
*\* help
Warning: /tmp/RtmpLGjw5s/Rbuild1ac13fe42a44/trajcomp/man/trajcomp-package.Rd:27: All text must be in a section
Warning: /tmp/RtmpLGjw5s/Rbuild1ac13fe42a44/trajcomp/man/trajcomp-package.Rd:28: All text must be in a section
**\* installing help indices
*\* building package indices
*\* installing vignettes
*\* testing if installed package can be loaded
**\* arch - i386
**\* arch - x64
- DONE (trajcomp)

**Comment by mwernerds** [comment]
The last line tells that despite a lot of warnings everything is working. Can you run library(trajcomp)? Then enter trajcomp:: and push TAB two times, it should show a lot of functions.
