### ISSUE TITLE
Help with installation on Windows needed

### ISSUE THREAD

**Issue by kalenkovich** [mwernerds/trajcomp#5]
I am trying to install `trajcomp` with the following command: 

`devtools::install_github('mwernerds/trajcomp/r-package')`

And I am getting the following error:

`Error: HTTP error 404.`

I assume I am doing it wrong. Could you please tell me how to do it right?

**Comment by kalenkovich** [comment]
Should have mentioned: I am on Windows 7.

**Comment by kalenkovich** [comment]
Here are the instructions for Windows:

1. Install `rtools` from [here](https://cran.r-project.org/bin/windows/Rtools/)
2. Install package `devtools` (`install.packages('devtools`))
3. Download and unzip the repository somewhere.
4. Open command window (Start -> cmd)
5. `cd` to wherever you unzipped the archive.
6. `cd trajcomp-master\r-package`
7.  `r --no-save <InstallDependencies.R`
8. Start R by running `R`
9. devtools::install('trajcomp')

**Comment by Priyanka-M96** [comment]
" Install rtools from 


This link is broken. Can I know the version number? 
This is the output I get while trying to run r --no-save <InstallDependencies.R

**Comment by kalenkovich** [comment]
Fixed the RTools link. The RTools version will depend on the R version.
